### ISSUE TITLE
Account Mapping for Lacework Integration with AWS Cloudtrail is failing 

### ISSUE THREAD

**Issue by jwechsler10** [lacework/terraform-provider-lacework#142]
Our organization has configured the `lacework_integration_aws_ct` Terraform resource with our org level CloudTrail recorder. All Cloudtrail logs from across our organization are showing up in Lacework. 

However, when we try to add the account mapping fields to the `lacework_integration_aws_ct` resource, it fails with the error below:

```
AccountMappingFile or AccountMapping is for Org Level Cloud trail Integration only.
│ 
│   with lacework_integration_aws_ct.root_account,
│   on organizations_cloudtrail.tf line 91, in resource "lacework_integration_aws_ct" "root_account":
│   91: resource "lacework_integration_aws_ct" "root_account" {
```

Any suggestions on how I can fix the mapping?

**Comment by afiune** [comment]
Hello @jwechsler10 👋🏽  - Thank you for reaching out to us, I am going to guess that the problem you are having is because the Lacework provider doesn't have the `organization = true` argument like:
```hcl
provider "lacework" {
  organization = true
}
```

This is needed to access organization-level data set and configure the organization-level integration. This argument is documented here https://registry.terraform.io/providers/lacework/lacework/latest/docs#organization-level-access

Having said that, we are lacking documentation that indicates that, when you use the `org_account_mappings` argument inside the `lacework_integration_aws_ct` resource, you must switch the provider to access the organization-level data sets.

Resouce documentation: https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_aws_ct

We are going to improve this documentation to explicitly mention this required configuration in the provider, something like this:
```hcl
provider "lacework" {
  organization = true
}

resource "lacework_integration_aws_ct" "consolidated" {
  name      = "Consolidated CloudTrail"
  queue_url = "https://sqs.us-west-2.amazonaws.com/123456789012/my_queue"
  credentials {
    role_arn    = "arn:aws:iam::1234567890:role/lacework_iam_example_role"
    external_id = "12345"
  }

  org_account_mappings {
    default_lacework_account = "lw_account_1"

    mapping {
      lacework_account = "lw_account_2"
      aws_accounts     = ["234556677", "774564564"]
    }

    mapping {
      lacework_account = "lw_account_3"
      aws_accounts     = ["553453453", "934534535"]
    }
  }
}
```

Please, let us know if adding this argument solves your problem.

**Comment by jwechsler10** [comment]
It seems to be getting further along, but now I am getting a 404 error. In the Lacework console I can see both the accounts that I am referencing in my terraform resource. Is that what is causing the 404, or is it not finding something else?

**Comment by afiune** [comment]
@jwechsler10 good that we are getting further along, would you be able to share more details about the `404` error? Do you see any message coming from our APIs? If you think that the error contains sensitive information, would you be able to open a support ticket with us to have a private and more direct way of communication?

**Comment by jwechsler10** [comment]
Do you know where I can see the API logs? At least in terraform it just tells me it is going to this URL:
`https://{our-company-name}.lacework.net/api/v2/CloudAccounts/{our-company-account-GUID}`.

The odd thing is when I make a GET request using Postman to hit the URL above, it works without any issue.

**Comment by afiune** [comment]
I will reach out to you first thing on Monday via our support ticket. Apologies in advance for the trouble here, we will get this sorted out together.

Have a great weekend!

**Comment by afiune** [comment]
JIRA: https://lacework.atlassian.net/browse/ALLY-611

**Comment by afiune** [comment]
@jwechsler10 already proposed some documentation changes, we would love to hear your feedback 👆🏽 🎉. !!

**Comment by afiune** [comment]
@jwechsler10 docs are live https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_aws_ct#migrating-an-existing-aws-cloudtrail-integration-to-the-organization-level

![tenor-63806176](https://user-images.githubusercontent.com/5712253/129830033-d8e14821-c37e-4a82-bdd4-9e0c45e3fd5d.gif)

**Comment by jwechsler10** [comment]
They look great! Much clearer now.
