### ISSUE TITLE
lacework_integration_aws_ct 403 unauthorized on first run, fine on subsequent runs.

### ISSUE THREAD

**Issue by JacobWeyer** [lacework/terraform-provider-lacework#153]
We frequently get these errors when running our terraform pipelines, and then the subsequent run goes with no issue.

```
Error: 
│   [GET] https://xometry.lacework.net/api/v2/CloudAccounts/XOMETRY8_09063B8C6458FAA00DD180B72331AB2E06E4548A64BB649
│   [403] Unauthorized Access
│ 
│   with lacework_integration_aws_ct.root_account,
│   on organizations_cloudtrail.tf line 91, in resource "lacework_integration_aws_ct" "root_account":
│   91: resource "lacework_integration_aws_ct" "root_account" {
```

Is there something we can do to prevent these errors from occurring? I'm assuming this is done by the provider to check for drift but frequently throws this error on the first few instances of the `lacework_integration_aws_ct` resource and then is fine for the rest.

Ex. We have it integrated with 18 accounts, the first 3-5 throw the error on the plan.

**Comment by afiune** [comment]
Hi @JacobWeyer - Thank you so much for your feedback, also, apologies that you are experiencing this issue.

We have already identified the problem and we are currently working on a solution as we speak, we are expecting
to have a solution by our next platform release. I am going to keep this bug open until the release goes live so that
you get informed as soon as we deploy it.

JIRA: https://lacework.atlassian.net/browse/RAIN-20092

**Comment by afiune** [comment]
Just checking back in, this has definitely been fixed! 💯
